"""Hand-curated extra quiz questions (5 per story) for the 24 freedom fighters
that the auto-generator couldn't cover reliably due to Pollinations.ai rate limits.

These are merged with quiz_extensions.py (which holds the 6 AI-generated ones)
in stories_seed.py so every story ends up with 10 quiz questions total.

Each entry follows the same shape as the base quizzes in stories_seed.py:
  {q_en, q_hi, options_en[4], options_hi[4], answer (0-3)}
"""

MANUAL_EXTRA_QUIZZES = {
    "rani-lakshmibai": [
        {"q_en": "What was Rani Lakshmibai's birth name?", "q_hi": "रानी लक्ष्मीबाई का बचपन का नाम क्या था?",
         "options_en": ["Manikarnika (Manu)", "Sita", "Anandi", "Padmavati"],
         "options_hi": ["मणिकर्णिका (मनु)", "सीता", "आनंदी", "पद्मावती"], "answer": 0},
        {"q_en": "Where was Rani Lakshmibai born?", "q_hi": "रानी लक्ष्मीबाई का जन्म कहाँ हुआ?",
         "options_en": ["Varanasi", "Pune", "Jhansi", "Gwalior"],
         "options_hi": ["वाराणसी", "पुणे", "झाँसी", "ग्वालियर"], "answer": 0},
        {"q_en": "What was the name of her favourite horse?", "q_hi": "उनके प्रिय घोड़े का नाम क्या था?",
         "options_en": ["Badal", "Chetak", "Sheran", "Bijli"],
         "options_hi": ["बादल", "चेतक", "शेरां", "बिजली"], "answer": 0},
        {"q_en": "Whom did she carry on her back into battle?", "q_hi": "वह युद्ध में अपनी पीठ पर किसे लेकर गईं?",
         "options_en": ["Her adopted son Damodar", "Her sister", "Her general", "A wounded soldier"],
         "options_hi": ["अपने गोद लिए पुत्र दामोदर को", "अपनी बहन को", "अपने सेनापति को", "एक घायल सैनिक को"], "answer": 0},
        {"q_en": "Her famous slogan was 'I will not give up my ___!'", "q_hi": "उनका प्रसिद्ध नारा था — 'मैं अपनी ___ नहीं दूँगी!'",
         "options_en": ["Jhansi", "Crown", "Sword", "Horse"],
         "options_hi": ["झाँसी", "ताज", "तलवार", "घोड़ा"], "answer": 0},
    ],
    "subhas-bose": [
        {"q_en": "By what nickname is Subhas Chandra Bose lovingly called?", "q_hi": "सुभाष चंद्र बोस को प्यार से किस नाम से बुलाया जाता है?",
         "options_en": ["Netaji", "Bapu", "Sardar", "Lokmanya"],
         "options_hi": ["नेताजी", "बापू", "सरदार", "लोकमान्य"], "answer": 0},
        {"q_en": "What army did Netaji lead?", "q_hi": "नेताजी ने कौन-सी सेना का नेतृत्व किया?",
         "options_en": ["Indian National Army (Azad Hind Fauj)", "British Indian Army", "Maratha Army", "Royal Air Force"],
         "options_hi": ["आज़ाद हिंद फ़ौज (INA)", "ब्रिटिश भारतीय सेना", "मराठा सेना", "रॉयल एयर फ़ोर्स"], "answer": 0},
        {"q_en": "Which famous slogan did Netaji give?", "q_hi": "नेताजी ने कौन सा प्रसिद्ध नारा दिया?",
         "options_en": ["Give me blood, I will give you freedom", "Swaraj is my birthright", "Do or die", "Vande Mataram"],
         "options_hi": ["तुम मुझे ख़ून दो, मैं तुम्हें आज़ादी दूँगा", "स्वराज मेरा जन्मसिद्ध अधिकार है", "करो या मरो", "वंदे मातरम्"], "answer": 0},
        {"q_en": "Where was Subhas Chandra Bose born?", "q_hi": "सुभाष चंद्र बोस का जन्म कहाँ हुआ?",
         "options_en": ["Cuttack, Odisha", "Calcutta", "Madras", "Delhi"],
         "options_hi": ["कटक, ओडिशा", "कलकत्ता", "मद्रास", "दिल्ली"], "answer": 0},
        {"q_en": "Netaji escaped from house arrest to which country first?", "q_hi": "नेताजी नज़रबंदी से भागकर पहले किस देश गए?",
         "options_en": ["Germany (via Afghanistan)", "Japan", "Russia", "America"],
         "options_hi": ["जर्मनी (अफ़ग़ानिस्तान होते हुए)", "जापान", "रूस", "अमेरिका"], "answer": 0},
    ],
    "chandrashekhar-azad": [
        {"q_en": "When asked his name as a teen, what did he reply?", "q_hi": "किशोरावस्था में जब नाम पूछा गया तो उन्होंने क्या कहा?",
         "options_en": ["Azad — Free!", "Chandrashekhar", "Bharat", "Krantikari"],
         "options_hi": ["आज़ाद — स्वतंत्र!", "चंद्रशेखर", "भारत", "क्रांतिकारी"], "answer": 0},
        {"q_en": "What promise did Azad keep till the end?", "q_hi": "आज़ाद ने अंत तक कौन सा वादा निभाया?",
         "options_en": ["Never to be captured alive", "Never to fight", "Never to speak", "Never to leave home"],
         "options_hi": ["कभी जीवित न पकड़ा जाऊँगा", "कभी न लड़ूँगा", "कभी न बोलूँगा", "कभी घर न छोड़ूँगा"], "answer": 0},
        {"q_en": "Where did Azad fight his last battle?", "q_hi": "आज़ाद ने अपनी अंतिम लड़ाई कहाँ लड़ी?",
         "options_en": ["Alfred Park, Allahabad", "Red Fort, Delhi", "Lahore Jail", "Howrah Bridge"],
         "options_hi": ["अल्फ्रेड पार्क, इलाहाबाद", "लाल किला, दिल्ली", "लाहौर जेल", "हावड़ा पुल"], "answer": 0},
        {"q_en": "What does Allahabad's Alfred Park now call itself?", "q_hi": "इलाहाबाद का अल्फ्रेड पार्क अब किस नाम से जाना जाता है?",
         "options_en": ["Azad Park", "Nehru Park", "Gandhi Park", "Bhagat Park"],
         "options_hi": ["आज़ाद पार्क", "नेहरू पार्क", "गांधी पार्क", "भगत पार्क"], "answer": 0},
        {"q_en": "Azad was a leader of which revolutionary group?", "q_hi": "आज़ाद किस क्रांतिकारी समूह के नेता थे?",
         "options_en": ["HSRA (Hindustan Socialist Republican Association)", "Congress", "Muslim League", "Arya Samaj"],
         "options_hi": ["HSRA (हिंदुस्तान सोशलिस्ट रिपब्लिकन एसोसिएशन)", "कांग्रेस", "मुस्लिम लीग", "आर्य समाज"], "answer": 0},
    ],
    "mangal-pandey": [
        {"q_en": "On which date did Mangal Pandey fire the first shot of 1857?", "q_hi": "मंगल पांडे ने 1857 की पहली गोली किस तारीख़ को चलाई?",
         "options_en": ["29 March 1857", "10 May 1857", "15 August 1857", "26 January 1857"],
         "options_hi": ["29 मार्च 1857", "10 मई 1857", "15 अगस्त 1857", "26 जनवरी 1857"], "answer": 0},
        {"q_en": "Where was Mangal Pandey stationed?", "q_hi": "मंगल पांडे की तैनाती कहाँ थी?",
         "options_en": ["Barrackpore", "Meerut", "Kanpur", "Lucknow"],
         "options_hi": ["बैरकपुर", "मेरठ", "कानपुर", "लखनऊ"], "answer": 0},
        {"q_en": "What insulted his faith in the new cartridges?", "q_hi": "नई कारतूसों में क्या बात उनकी आस्था के विरुद्ध थी?",
         "options_en": ["Greased with cow/pig fat", "Too heavy", "Made of gold", "Painted black"],
         "options_hi": ["गाय/सूअर की चर्बी से सने थे", "बहुत भारी थे", "सोने के थे", "काले रंगे थे"], "answer": 0},
        {"q_en": "What rank did Mangal Pandey hold?", "q_hi": "मंगल पांडे का पद क्या था?",
         "options_en": ["Sepoy", "General", "Captain", "Colonel"],
         "options_hi": ["सिपाही", "जनरल", "कैप्टन", "कर्नल"], "answer": 0},
        {"q_en": "He sparked which great event in Indian history?", "q_hi": "उन्होंने भारतीय इतिहास की कौन सी बड़ी घटना की चिंगारी जलाई?",
         "options_en": ["First War of Independence 1857", "Salt March", "Quit India 1942", "Partition 1947"],
         "options_hi": ["1857 का प्रथम स्वतंत्रता संग्राम", "नमक यात्रा", "1942 का भारत छोड़ो आंदोलन", "1947 का विभाजन"], "answer": 0},
    ],
    "sardar-patel": [
        {"q_en": "By what title is Sardar Patel famously known?", "q_hi": "सरदार पटेल को किस उपाधि से जाना जाता है?",
         "options_en": ["Iron Man of India", "Father of Nation", "Lion of Punjab", "Light of Asia"],
         "options_hi": ["भारत का लौह पुरुष", "राष्ट्रपिता", "पंजाब केसरी", "एशिया की रोशनी"], "answer": 0},
        {"q_en": "How many princely states did Patel unite into India?", "q_hi": "पटेल ने कितने रियासतों को भारत में मिलाया?",
         "options_en": ["562", "100", "1000", "50"],
         "options_hi": ["562", "100", "1000", "50"], "answer": 0},
        {"q_en": "Which Gujarat satyagraha did Patel lead in 1928?", "q_hi": "पटेल ने 1928 में गुजरात के किस सत्याग्रह का नेतृत्व किया?",
         "options_en": ["Bardoli Satyagraha", "Champaran Satyagraha", "Kheda Satyagraha", "Dandi March"],
         "options_hi": ["बारडोली सत्याग्रह", "चंपारण सत्याग्रह", "खेड़ा सत्याग्रह", "नमक यात्रा"], "answer": 0},
        {"q_en": "Where is Sardar Patel's famous Statue of Unity located?", "q_hi": "सरदार पटेल की 'स्टैच्यू ऑफ़ यूनिटी' कहाँ स्थित है?",
         "options_en": ["Kevadia, Gujarat", "Delhi", "Mumbai", "Hyderabad"],
         "options_hi": ["केवड़िया, गुजरात", "दिल्ली", "मुंबई", "हैदराबाद"], "answer": 0},
        {"q_en": "What was Patel's profession before joining freedom struggle?", "q_hi": "स्वतंत्रता संग्राम से पहले पटेल का पेशा क्या था?",
         "options_en": ["Lawyer (barrister)", "Doctor", "Teacher", "Soldier"],
         "options_hi": ["वकील (बैरिस्टर)", "डॉक्टर", "शिक्षक", "सैनिक"], "answer": 0},
    ],
    "lala-lajpat-rai": [
        {"q_en": "By what title was Lala Lajpat Rai known?", "q_hi": "लाला लाजपत राय किस उपाधि से जाने जाते थे?",
         "options_en": ["Punjab Kesari (Lion of Punjab)", "Sher-e-Bharat", "Loknayak", "Veer"],
         "options_hi": ["पंजाब केसरी (पंजाब का शेर)", "शेर-ए-भारत", "लोकनायक", "वीर"], "answer": 0},
        {"q_en": "Which 1928 commission did he protest against?", "q_hi": "उन्होंने 1928 के किस आयोग का विरोध किया?",
         "options_en": ["Simon Commission", "Cripps Mission", "Cabinet Mission", "Rowlatt Committee"],
         "options_hi": ["साइमन कमीशन", "क्रिप्स मिशन", "कैबिनेट मिशन", "रौलट समिति"], "answer": 0},
        {"q_en": "Which trio was he part of? 'Lal-Bal-___'", "q_hi": "वह 'लाल-बाल-___' त्रिमूर्ति का हिस्सा थे।",
         "options_en": ["Pal", "Singh", "Rai", "Patel"],
         "options_hi": ["पाल", "सिंह", "राय", "पटेल"], "answer": 0},
        {"q_en": "What injury caused his death?", "q_hi": "किस चोट के कारण उनका निधन हुआ?",
         "options_en": ["Lathi-charge wounds", "Bullet wound", "Snake bite", "Fall from horse"],
         "options_hi": ["लाठीचार्ज की चोटें", "गोली का घाव", "साँप का काटना", "घोड़े से गिरना"], "answer": 0},
        {"q_en": "Whose attack did Bhagat Singh & Rajguru avenge for Lala-ji?", "q_hi": "लाला जी का बदला किसके हमले से भगत सिंह और राजगुरु ने लिया?",
         "options_en": ["British officer Saunders", "King George", "Lord Mountbatten", "Lord Curzon"],
         "options_hi": ["ब्रिटिश अधिकारी सॉन्डर्स", "किंग जॉर्ज", "लॉर्ड माउंटबेटन", "लॉर्ड कर्ज़न"], "answer": 0},
    ],
    "rajguru": [
        {"q_en": "Rajguru was famous as a what?", "q_hi": "राजगुरु किस कौशल के लिए प्रसिद्ध थे?",
         "options_en": ["Sharp marksman", "Poet", "Lawyer", "Singer"],
         "options_hi": ["तेज़ निशानेबाज़", "कवि", "वकील", "गायक"], "answer": 0},
        {"q_en": "With which two friends was Rajguru hanged?", "q_hi": "राजगुरु को किन दो साथियों के साथ फाँसी दी गई?",
         "options_en": ["Bhagat Singh & Sukhdev", "Azad & Bose", "Tilak & Pal", "Bose & Patel"],
         "options_hi": ["भगत सिंह और सुखदेव", "आज़ाद और बोस", "तिलक और पाल", "बोस और पटेल"], "answer": 0},
        {"q_en": "In which year were they hanged?", "q_hi": "उन्हें किस वर्ष फाँसी दी गई?",
         "options_en": ["1931", "1857", "1942", "1947"],
         "options_hi": ["1931", "1857", "1942", "1947"], "answer": 0},
        {"q_en": "Rajguru came from which Indian state?", "q_hi": "राजगुरु किस राज्य से थे?",
         "options_en": ["Maharashtra", "Punjab", "Bengal", "Gujarat"],
         "options_hi": ["महाराष्ट्र", "पंजाब", "बंगाल", "गुजरात"], "answer": 0},
        {"q_en": "How old was Rajguru at the time of his death?", "q_hi": "बलिदान के समय राजगुरु की उम्र क्या थी?",
         "options_en": ["22", "30", "45", "60"],
         "options_hi": ["22", "30", "45", "60"], "answer": 0},
    ],
    "khudiram-bose": [
        {"q_en": "How old was Khudiram Bose when he was hanged?", "q_hi": "फाँसी के समय खुदीराम बोस की उम्र क्या थी?",
         "options_en": ["18", "25", "30", "16"],
         "options_hi": ["18", "25", "30", "16"], "answer": 0},
        {"q_en": "Where did Khudiram throw his bomb in 1908?", "q_hi": "खुदीराम ने 1908 में बम कहाँ फेंका?",
         "options_en": ["Muzaffarpur", "Calcutta", "Delhi", "Lahore"],
         "options_hi": ["मुज़फ़्फ़रपुर", "कलकत्ता", "दिल्ली", "लाहौर"], "answer": 0},
        {"q_en": "Khudiram is honoured as the YOUNGEST what?", "q_hi": "खुदीराम को सबसे कम उम्र के क्या होने का सम्मान मिला है?",
         "options_en": ["Revolutionary to be hanged", "Painter", "Poet", "Singer"],
         "options_hi": ["फाँसी पर चढ़ने वाले क्रांतिकारी", "चित्रकार", "कवि", "गायक"], "answer": 0},
        {"q_en": "From which Indian state did Khudiram come?", "q_hi": "खुदीराम किस राज्य से थे?",
         "options_en": ["Bengal", "Punjab", "Maharashtra", "Madras"],
         "options_hi": ["बंगाल", "पंजाब", "महाराष्ट्र", "मद्रास"], "answer": 0},
        {"q_en": "Smiling, what did Khudiram do walking to the gallows?", "q_hi": "फाँसी की ओर जाते समय खुदीराम क्या कर रहे थे?",
         "options_en": ["Smiled at his country", "Cried", "Stayed silent", "Spoke in Latin"],
         "options_hi": ["देश को देखकर मुस्कुराए", "रोए", "मौन रहे", "लैटिन में बोले"], "answer": 0},
    ],
    "surya-sen": [
        {"q_en": "By what loving title was Surya Sen called?", "q_hi": "सूर्य सेन को प्यार से किस नाम से बुलाया जाता था?",
         "options_en": ["Master-da", "Netaji", "Bapu", "Sardar"],
         "options_hi": ["मास्टर-दा", "नेताजी", "बापू", "सरदार"], "answer": 0},
        {"q_en": "Which 1930 raid did he lead?", "q_hi": "उन्होंने 1930 के किस छापे का नेतृत्व किया?",
         "options_en": ["Chittagong Armoury Raid", "Kakori Train Robbery", "Surat Salt Raid", "Lahore Bank Raid"],
         "options_hi": ["चटगाँव शस्त्रागार छापा", "काकोरी ट्रेन डकैती", "सूरत नमक छापा", "लाहौर बैंक छापा"], "answer": 0},
        {"q_en": "What was Master-da's profession?", "q_hi": "मास्टर-दा का पेशा क्या था?",
         "options_en": ["School teacher", "Doctor", "Engineer", "Lawyer"],
         "options_hi": ["स्कूल शिक्षक", "डॉक्टर", "इंजीनियर", "वकील"], "answer": 0},
        {"q_en": "Surya Sen was from which Indian state?", "q_hi": "सूर्य सेन किस राज्य से थे?",
         "options_en": ["Bengal", "Bihar", "Odisha", "Assam"],
         "options_hi": ["बंगाल", "बिहार", "ओडिशा", "असम"], "answer": 0},
        {"q_en": "Who was a famous female revolutionary trained by Master-da?", "q_hi": "मास्टर-दा द्वारा प्रशिक्षित एक प्रसिद्ध क्रांतिकारी महिला कौन थीं?",
         "options_en": ["Kalpana Datta", "Sarojini Naidu", "Rani Lakshmibai", "Aruna Asaf Ali"],
         "options_hi": ["कल्पना दत्ता", "सरोजिनी नायडू", "रानी लक्ष्मीबाई", "अरुणा आसफ अली"], "answer": 0},
    ],
    "bagha-jatin": [
        {"q_en": "Why was Jatindranath called 'Bagha' (Tiger)?", "q_hi": "जतीन्द्रनाथ को 'बाघा' क्यों कहा गया?",
         "options_en": ["He killed a tiger with bare hands", "He had striped clothes", "He was a vet", "He owned a tiger"],
         "options_hi": ["उन्होंने ख़ाली हाथों से बाघ मारा था", "उनके धारीदार कपड़े थे", "वह पशु चिकित्सक थे", "वह बाघ पालते थे"], "answer": 0},
        {"q_en": "Where did Bagha Jatin make his last stand?", "q_hi": "बाघा जतीन ने अंतिम लड़ाई कहाँ लड़ी?",
         "options_en": ["Balasore, Odisha", "Calcutta", "Delhi", "Madras"],
         "options_hi": ["बालासोर, ओडिशा", "कलकत्ता", "दिल्ली", "मद्रास"], "answer": 0},
        {"q_en": "Bagha Jatin came from which Indian state?", "q_hi": "बाघा जतीन किस राज्य के थे?",
         "options_en": ["Bengal", "Punjab", "Tamil Nadu", "Rajasthan"],
         "options_hi": ["बंगाल", "पंजाब", "तमिल नाडु", "राजस्थान"], "answer": 0},
        {"q_en": "What is one quality his story teaches us?", "q_hi": "उनकी कहानी हमें क्या सिखाती है?",
         "options_en": ["Fearless courage", "Greed", "Hatred", "Laziness"],
         "options_hi": ["निडर साहस", "लालच", "नफ़रत", "आलस"], "answer": 0},
        {"q_en": "Bagha Jatin was a leader of which group?", "q_hi": "बाघा जतीन किस समूह के नेता थे?",
         "options_en": ["Jugantar revolutionaries", "Congress", "Muslim League", "Khalsa"],
         "options_hi": ["जुगांतर क्रांतिकारी", "कांग्रेस", "मुस्लिम लीग", "ख़ालसा"], "answer": 0},
    ],
    "matangini-hazra": [
        {"q_en": "At what age did Matangini Hazra lead the procession?", "q_hi": "मातंगिनी हाज़रा ने जुलूस का नेतृत्व किस उम्र में किया?",
         "options_en": ["73", "20", "40", "90"],
         "options_hi": ["73", "20", "40", "90"], "answer": 0},
        {"q_en": "What lovingly was Matangini called by villagers?", "q_hi": "ग्रामीण उन्हें प्यार से क्या कहते थे?",
         "options_en": ["Gandhi Buri (old Gandhi)", "Maa", "Devi", "Rani"],
         "options_hi": ["गांधी बुड़ी (वृद्ध गांधी)", "माँ", "देवी", "रानी"], "answer": 0},
        {"q_en": "She was shot while holding what?", "q_hi": "गोली लगने के समय वह क्या थामे थीं?",
         "options_en": ["The Indian tricolor", "A book", "A sword", "A lamp"],
         "options_hi": ["भारतीय तिरंगा", "एक किताब", "एक तलवार", "एक दीपक"], "answer": 0},
        {"q_en": "Matangini's brave act was in which movement?", "q_hi": "मातंगिनी का बलिदान किस आंदोलन में हुआ?",
         "options_en": ["Quit India 1942", "Salt March 1930", "1857 Revolt", "Swadeshi 1905"],
         "options_hi": ["भारत छोड़ो 1942", "नमक यात्रा 1930", "1857 का विद्रोह", "स्वदेशी 1905"], "answer": 0},
        {"q_en": "From which Indian state was Matangini?", "q_hi": "मातंगिनी किस राज्य की थीं?",
         "options_en": ["Bengal (Tamluk)", "Bihar", "Punjab", "Maharashtra"],
         "options_hi": ["बंगाल (तामलुक)", "बिहार", "पंजाब", "महाराष्ट्र"], "answer": 0},
    ],
    "bipin-pal": [
        {"q_en": "Bipin Chandra Pal was part of which trio?", "q_hi": "बिपिन चंद्र पाल किस त्रिमूर्ति का हिस्सा थे?",
         "options_en": ["Lal-Bal-Pal", "Tilak-Gokhale-Gandhi", "Bose-Patel-Nehru", "Naoroji-Pal-Banerjee"],
         "options_hi": ["लाल-बाल-पाल", "तिलक-गोखले-गांधी", "बोस-पटेल-नेहरू", "नौरोजी-पाल-बैनर्जी"], "answer": 0},
        {"q_en": "Which Bengal-led movement did Pal champion in 1905?", "q_hi": "1905 में पाल ने बंगाल के किस आंदोलन का नेतृत्व किया?",
         "options_en": ["Swadeshi Movement", "Salt March", "Quit India", "Khilafat"],
         "options_hi": ["स्वदेशी आंदोलन", "नमक यात्रा", "भारत छोड़ो", "ख़िलाफ़त"], "answer": 0},
        {"q_en": "What was Pal's main weapon as an activist?", "q_hi": "एक कार्यकर्ता के रूप में पाल का मुख्य हथियार क्या था?",
         "options_en": ["His powerful speeches and writing", "Sword", "Bombs", "Charkha"],
         "options_hi": ["उनके सशक्त भाषण और लेख", "तलवार", "बम", "चरखा"], "answer": 0},
        {"q_en": "Which English-language paper did Pal edit?", "q_hi": "पाल ने कौन सा अंग्रेज़ी अख़बार संपादित किया?",
         "options_en": ["Bande Mataram", "The Hindu", "Times of India", "Statesman"],
         "options_hi": ["बंदे मातरम्", "द हिंदू", "टाइम्स ऑफ़ इंडिया", "स्टेट्समैन"], "answer": 0},
        {"q_en": "Bipin Pal was from which state?", "q_hi": "बिपिन पाल किस राज्य के थे?",
         "options_en": ["Bengal (Sylhet)", "Punjab", "Maharashtra", "Gujarat"],
         "options_hi": ["बंगाल (सिलहट)", "पंजाब", "महाराष्ट्र", "गुजरात"], "answer": 0},
    ],
    "veer-savarkar": [
        {"q_en": "In which infamous jail was Savarkar imprisoned?", "q_hi": "सावरकर किस कुख्यात जेल में क़ैद रहे?",
         "options_en": ["Cellular Jail, Andaman", "Tihar Jail", "Lahore Jail", "Howrah Jail"],
         "options_hi": ["सेलुलर जेल, अंडमान", "तिहाड़ जेल", "लाहौर जेल", "हावड़ा जेल"], "answer": 0},
        {"q_en": "What 'kala pani' means?", "q_hi": "'काला पानी' का क्या अर्थ है?",
         "options_en": ["Punishment of being exiled across the sea", "Black drinking water", "Toxic ocean", "Punjabi sweet"],
         "options_hi": ["समुद्र पार निर्वासन की सज़ा", "काले रंग का पानी", "ज़हरीला सागर", "पंजाबी मिठाई"], "answer": 0},
        {"q_en": "What was Savarkar's mother tongue?", "q_hi": "सावरकर की मातृभाषा क्या थी?",
         "options_en": ["Marathi", "Bengali", "Hindi", "Tamil"],
         "options_hi": ["मराठी", "बंगाली", "हिंदी", "तमिल"], "answer": 0},
        {"q_en": "Savarkar famously jumped off a moving ship to escape near which city?", "q_hi": "सावरकर ने भागने के लिए किस शहर के पास चलते जहाज़ से छलाँग लगाई?",
         "options_en": ["Marseille (France)", "London", "Mumbai", "Lisbon"],
         "options_hi": ["मार्सेय (फ्रांस)", "लंदन", "मुंबई", "लिस्बन"], "answer": 0},
        {"q_en": "Which honorific is added before his name?", "q_hi": "उनके नाम के पहले कौन सी उपाधि लगाई जाती है?",
         "options_en": ["Veer (Brave)", "Acharya", "Pandit", "Sahib"],
         "options_hi": ["वीर (बहादुर)", "आचार्य", "पंडित", "साहिब"], "answer": 0},
    ],
    "madam-cama": [
        {"q_en": "Where did Madam Cama unfurl India's first flag in 1907?", "q_hi": "मैडम कामा ने 1907 में भारत का पहला झंडा कहाँ फहराया?",
         "options_en": ["Stuttgart, Germany", "London", "New York", "Paris"],
         "options_hi": ["स्टटगार्ट, जर्मनी", "लंदन", "न्यूयॉर्क", "पेरिस"], "answer": 0},
        {"q_en": "What slogan was on her flag?", "q_hi": "उनके झंडे पर कौन सा नारा था?",
         "options_en": ["Vande Mataram", "Jai Hind", "Inquilab Zindabad", "Swaraj"],
         "options_hi": ["वंदे मातरम्", "जय हिंद", "इंक़लाब ज़िंदाबाद", "स्वराज"], "answer": 0},
        {"q_en": "What community did Madam Cama belong to?", "q_hi": "मैडम कामा किस समुदाय से थीं?",
         "options_en": ["Parsi", "Sikh", "Bengali Hindu", "Maratha"],
         "options_hi": ["पारसी", "सिख", "बंगाली हिंदू", "मराठा"], "answer": 0},
        {"q_en": "What is Madam Cama lovingly called?", "q_hi": "मैडम कामा को प्यार से क्या कहा जाता है?",
         "options_en": ["Mother of Indian Revolution Abroad", "Sister of Freedom", "Queen of Speech", "Empress of Letters"],
         "options_hi": ["विदेश में भारतीय क्रांति की माँ", "स्वतंत्रता की बहन", "वाणी की रानी", "अक्षरों की महारानी"], "answer": 0},
        {"q_en": "Which city was Madam Cama born in?", "q_hi": "मैडम कामा का जन्म किस शहर में हुआ?",
         "options_en": ["Bombay (Mumbai)", "Surat", "Calcutta", "Delhi"],
         "options_hi": ["बम्बई (मुंबई)", "सूरत", "कलकत्ता", "दिल्ली"], "answer": 0},
    ],
    "tantia-tope": [
        {"q_en": "Who was Tantia Tope's childhood friend?", "q_hi": "तांत्या टोपे के बचपन के मित्र कौन थे?",
         "options_en": ["Rani Lakshmibai", "Nana Sahib", "Begum Hazrat Mahal", "Mangal Pandey"],
         "options_hi": ["रानी लक्ष्मीबाई", "नाना साहिब", "बेगम हज़रत महल", "मंगल पांडे"], "answer": 0},
        {"q_en": "Tantia Tope was a master of which kind of warfare?", "q_hi": "तांत्या टोपे किस तरह के युद्ध में माहिर थे?",
         "options_en": ["Guerrilla (chhapamar) warfare", "Naval warfare", "Air strikes", "Trench warfare"],
         "options_hi": ["छापामार युद्ध", "नौसैनिक युद्ध", "हवाई हमले", "खाई युद्ध"], "answer": 0},
        {"q_en": "Tantia Tope fought how many battles in 12 months?", "q_hi": "तांत्या टोपे ने 12 महीनों में कितनी लड़ाइयाँ लड़ीं?",
         "options_en": ["About 150", "5", "20", "1000"],
         "options_hi": ["लगभग 150", "5", "20", "1000"], "answer": 0},
        {"q_en": "From which region did Tantia Tope hail?", "q_hi": "तांत्या टोपे किस क्षेत्र से थे?",
         "options_en": ["Maharashtra", "Bengal", "Punjab", "Tamil Nadu"],
         "options_hi": ["महाराष्ट्र", "बंगाल", "पंजाब", "तमिल नाडु"], "answer": 0},
        {"q_en": "Which year was Tantia Tope's great revolt?", "q_hi": "तांत्या टोपे का महान विद्रोह किस वर्ष था?",
         "options_en": ["1857", "1942", "1905", "1919"],
         "options_hi": ["1857", "1942", "1905", "1919"], "answer": 0},
    ],
    "subramania-bharati": [
        {"q_en": "What was Bharati's profession?", "q_hi": "भारती का पेशा क्या था?",
         "options_en": ["Tamil poet", "Soldier", "Doctor", "Engineer"],
         "options_hi": ["तमिल कवि", "सैनिक", "डॉक्टर", "इंजीनियर"], "answer": 0},
        {"q_en": "By which title is Bharati honoured?", "q_hi": "भारती को किस उपाधि से सम्मानित किया जाता है?",
         "options_en": ["Mahakavi (Great Poet)", "Mahatma", "Lokmanya", "Veer"],
         "options_hi": ["महाकवि", "महात्मा", "लोकमान्य", "वीर"], "answer": 0},
        {"q_en": "His most famous patriotic song begins 'Achamillai ___'", "q_hi": "उनका प्रसिद्ध देशभक्ति गीत 'अच्चमिल्लै ___' से शुरू होता है।",
         "options_en": ["Achamillai (No fear, no fear)", "Vande Mataram", "Jai Hind", "Sare Jahan"],
         "options_hi": ["अच्चमिल्लै (कोई भय नहीं)", "वंदे मातरम्", "जय हिंद", "सारे जहाँ"], "answer": 0},
        {"q_en": "Bharati was from which state?", "q_hi": "भारती किस राज्य से थे?",
         "options_en": ["Tamil Nadu", "Kerala", "Andhra Pradesh", "Karnataka"],
         "options_hi": ["तमिल नाडु", "केरल", "आंध्र प्रदेश", "कर्नाटक"], "answer": 0},
        {"q_en": "Bharati wrote in support of which cause for women?", "q_hi": "महिलाओं के लिए भारती ने किस उद्देश्य का समर्थन किया?",
         "options_en": ["Women's freedom and education", "Veiling", "Silent obedience", "Early marriage"],
         "options_hi": ["स्त्री स्वतंत्रता और शिक्षा", "घूंघट", "मौन आज्ञापालन", "बाल विवाह"], "answer": 0},
    ],
    "alluri-sitarama-raju": [
        {"q_en": "Alluri led which rebellion in 1922?", "q_hi": "अल्लूरी ने 1922 में किस विद्रोह का नेतृत्व किया?",
         "options_en": ["Rampa Rebellion", "Sepoy Mutiny", "Khilafat", "Champaran"],
         "options_hi": ["रामपा विद्रोह", "सिपाही विद्रोह", "ख़िलाफ़त", "चंपारण"], "answer": 0},
        {"q_en": "What was his loving title?", "q_hi": "उनकी प्रिय उपाधि क्या थी?",
         "options_en": ["Manyam Veerudu (Hero of the Forest)", "Singham", "Veerveer", "Yuvraj"],
         "options_hi": ["मन्यम वीरुडु (वन का नायक)", "सिंघम", "वीरवीर", "युवराज"], "answer": 0},
        {"q_en": "From which Indian state was Alluri?", "q_hi": "अल्लूरी किस राज्य से थे?",
         "options_en": ["Andhra Pradesh", "Telangana", "Tamil Nadu", "Karnataka"],
         "options_hi": ["आंध्र प्रदेश", "तेलंगाना", "तमिल नाडु", "कर्नाटक"], "answer": 0},
        {"q_en": "Whom did he rally to fight?", "q_hi": "उन्होंने किसे संगठित किया?",
         "options_en": ["Tribal (Adivasi) communities", "Princes", "Soldiers", "Merchants"],
         "options_hi": ["आदिवासी समुदाय", "राजकुमार", "सैनिक", "व्यापारी"], "answer": 0},
        {"q_en": "Alluri became a famous icon thanks to which 2022 movie?", "q_hi": "2022 की किस फ़िल्म ने अल्लूरी को नई पीढ़ी में लोकप्रिय बनाया?",
         "options_en": ["RRR", "Bahubali", "Padmaavat", "Lagaan"],
         "options_hi": ["RRR", "बाहुबली", "पद्मावत", "लगान"], "answer": 0},
    ],
    "velu-thampi": [
        {"q_en": "Velu Thampi was Prime Minister (Dalawa) of which kingdom?", "q_hi": "वेलू थम्पी किस राज्य के प्रधान (दलवा) थे?",
         "options_en": ["Travancore (Kerala)", "Mysore", "Hyderabad", "Awadh"],
         "options_hi": ["त्रावणकोर (केरल)", "मैसूर", "हैदराबाद", "अवध"], "answer": 0},
        {"q_en": "His famous 1809 declaration is called?", "q_hi": "उनकी प्रसिद्ध 1809 की घोषणा क्या कहलाती है?",
         "options_en": ["Kundara Proclamation", "Lahore Declaration", "Surat Decree", "Pune Manifesto"],
         "options_hi": ["कुंदरा घोषणा", "लाहौर घोषणा", "सूरत आदेश", "पुणे घोषणापत्र"], "answer": 0},
        {"q_en": "Against whom did Velu Thampi raise revolt?", "q_hi": "वेलू थम्पी ने किसके विरुद्ध विद्रोह किया?",
         "options_en": ["British East India Company", "Mughals", "Marathas", "Portuguese"],
         "options_hi": ["ब्रिटिश ईस्ट इंडिया कंपनी", "मुग़ल", "मराठा", "पुर्तगाली"], "answer": 0},
        {"q_en": "In which century did Velu Thampi live?", "q_hi": "वेलू थम्पी किस सदी में जिए?",
         "options_en": ["Early 19th century", "16th century", "17th century", "20th century"],
         "options_hi": ["19वीं सदी की शुरुआत", "16वीं सदी", "17वीं सदी", "20वीं सदी"], "answer": 0},
        {"q_en": "What does Velu Thampi inspire today?", "q_hi": "वेलू थम्पी आज क्या प्रेरणा देते हैं?",
         "options_en": ["Early resistance against the British", "Trade with Europeans", "Art and music", "Sports"],
         "options_hi": ["अंग्रेज़ों के विरुद्ध प्रारंभिक प्रतिरोध", "यूरोपियों से व्यापार", "कला और संगीत", "खेल"], "answer": 0},
    ],
    "begum-hazrat-mahal": [
        {"q_en": "Begum Hazrat Mahal was queen of which kingdom?", "q_hi": "बेगम हज़रत महल किस राज्य की रानी थीं?",
         "options_en": ["Awadh (Oudh)", "Hyderabad", "Mysore", "Jhansi"],
         "options_hi": ["अवध (ऊध)", "हैदराबाद", "मैसूर", "झाँसी"], "answer": 0},
        {"q_en": "She led the revolt of 1857 from which city?", "q_hi": "उन्होंने 1857 का विद्रोह किस शहर से नेतृत्व किया?",
         "options_en": ["Lucknow", "Delhi", "Kanpur", "Patna"],
         "options_hi": ["लखनऊ", "दिल्ली", "कानपुर", "पटना"], "answer": 0},
        {"q_en": "What was the name of her young son crowned king?", "q_hi": "उनके युवा बेटे का नाम क्या था जिसे राजा बनाया गया?",
         "options_en": ["Birjis Qadr", "Wajid Ali", "Akbar Shah", "Salim"],
         "options_hi": ["बिर्जिस क़ादर", "वाजिद अली", "अकबर शाह", "सलीम"], "answer": 0},
        {"q_en": "Where did she go in exile?", "q_hi": "वह निर्वासन में कहाँ गईं?",
         "options_en": ["Nepal", "Burma", "Persia", "Sri Lanka"],
         "options_hi": ["नेपाल", "बर्मा", "फ़ारस", "श्रीलंका"], "answer": 0},
        {"q_en": "What does Begum Hazrat Mahal teach us?", "q_hi": "बेगम हज़रत महल हमें क्या सिखाती हैं?",
         "options_en": ["Mothers can be brave warriors too", "Always stay quiet", "Never trust friends", "Avoid duty"],
         "options_hi": ["माँ भी वीर योद्धा बन सकती हैं", "हमेशा चुप रहें", "मित्रों पर भरोसा न करें", "कर्तव्य से बचें"], "answer": 0},
        {"q_en": "Who was her husband, exiled by the British?", "q_hi": "उनके पति कौन थे, जिन्हें अंग्रेज़ों ने निर्वासित किया?",
         "options_en": ["Nawab Wajid Ali Shah", "Bahadur Shah Zafar", "Tipu Sultan", "Nana Sahib"],
         "options_hi": ["नवाब वाजिद अली शाह", "बहादुर शाह ज़फ़र", "टीपू सुल्तान", "नाना साहिब"], "answer": 0},
    ],
    "sukhdev": [
        {"q_en": "Sukhdev was hanged with which two friends?", "q_hi": "सुखदेव को किन दो साथियों के साथ फाँसी दी गई?",
         "options_en": ["Bhagat Singh & Rajguru", "Azad & Bose", "Tilak & Pal", "Nehru & Patel"],
         "options_hi": ["भगत सिंह और राजगुरु", "आज़ाद और बोस", "तिलक और पाल", "नेहरू और पटेल"], "answer": 0},
        {"q_en": "In which year was Sukhdev martyred?", "q_hi": "सुखदेव को किस वर्ष शहीद किया गया?",
         "options_en": ["1931", "1857", "1942", "1947"],
         "options_hi": ["1931", "1857", "1942", "1947"], "answer": 0},
        {"q_en": "How old was Sukhdev when he was hanged?", "q_hi": "फाँसी के समय सुखदेव की उम्र क्या थी?",
         "options_en": ["23", "30", "40", "60"],
         "options_hi": ["23", "30", "40", "60"], "answer": 0},
        {"q_en": "Sukhdev was a member of which revolutionary group?", "q_hi": "सुखदेव किस क्रांतिकारी समूह के सदस्य थे?",
         "options_en": ["HSRA (Hindustan Socialist Republican Association)", "Congress", "Khudai Khidmatgar", "Muslim League"],
         "options_hi": ["HSRA (हिंदुस्तान सोशलिस्ट रिपब्लिकन एसोसिएशन)", "कांग्रेस", "खुदाई खिदमतगार", "मुस्लिम लीग"], "answer": 0},
        {"q_en": "From which Indian state was Sukhdev?", "q_hi": "सुखदेव किस राज्य के थे?",
         "options_en": ["Punjab", "Bengal", "Maharashtra", "Tamil Nadu"],
         "options_hi": ["पंजाब", "बंगाल", "महाराष्ट्र", "तमिल नाडु"], "answer": 0},
        {"q_en": "Sukhdev gave his life smiling for whose freedom?", "q_hi": "सुखदेव ने मुस्कुराते हुए किसके लिए प्राण दिए?",
         "options_en": ["Mother India", "His family only", "His village", "His school"],
         "options_hi": ["भारत माता", "केवल अपने परिवार", "अपना गाँव", "अपना स्कूल"], "answer": 0},
    ],
    "kittur-chennamma": [
        {"q_en": "In which year did Chennamma defeat the British?", "q_hi": "चेन्नम्मा ने अंग्रेज़ों को किस वर्ष हराया?",
         "options_en": ["1824", "1857", "1900", "1700"],
         "options_hi": ["1824", "1857", "1900", "1700"], "answer": 0},
        {"q_en": "Kittur Chennamma was queen of which region?", "q_hi": "कित्तूर चेन्नम्मा किस क्षेत्र की रानी थीं?",
         "options_en": ["Kittur, Karnataka", "Mysore", "Jhansi", "Lucknow"],
         "options_hi": ["कित्तूर, कर्नाटक", "मैसूर", "झाँसी", "लखनऊ"], "answer": 0},
        {"q_en": "Why was the British 'Doctrine of Lapse' attempted on Kittur?", "q_hi": "अंग्रेज़ों ने कित्तूर पर 'लैप्स की नीति' क्यों लागू की?",
         "options_en": ["She had adopted a son as heir", "She was old", "She refused trade", "She built a fort"],
         "options_hi": ["उन्होंने एक गोद लिए पुत्र को उत्तराधिकारी बनाया", "वह वृद्ध थीं", "उन्होंने व्यापार से इनकार किया", "उन्होंने किला बनाया"], "answer": 0},
        {"q_en": "Chennamma is honoured as the FIRST warrior queen to do what?", "q_hi": "चेन्नम्मा कौन सी पहली वीर रानी के रूप में पूजी जाती हैं?",
         "options_en": ["Defeat the British in battle", "Cross the Himalayas", "Sail to Africa", "Compose a Veda"],
         "options_hi": ["अंग्रेज़ों को युद्ध में हराने वाली", "हिमालय पार करने वाली", "अफ़्रीका जाने वाली", "वेद रचने वाली"], "answer": 0},
        {"q_en": "Chennamma's bravery came before which queen's revolt?", "q_hi": "चेन्नम्मा की वीरता किस रानी से पहले की है?",
         "options_en": ["Rani Lakshmibai (1857)", "Razia Sultan", "Indira Gandhi", "Ahilyabai"],
         "options_hi": ["रानी लक्ष्मीबाई (1857)", "रज़िया सुल्तान", "इंदिरा गांधी", "अहिल्याबाई"], "answer": 0},
    ],
    "aruna-asaf-ali": [
        {"q_en": "On which date did Aruna hoist the flag at Gowalia Tank?", "q_hi": "अरुणा ने गोवालिया टैंक पर झंडा किस तारीख़ को फहराया?",
         "options_en": ["9 August 1942", "15 August 1947", "26 January 1950", "2 October 1869"],
         "options_hi": ["9 अगस्त 1942", "15 अगस्त 1947", "26 जनवरी 1950", "2 अक्टूबर 1869"], "answer": 0},
        {"q_en": "Which movement did this launch?", "q_hi": "इससे कौन सा आंदोलन शुरू हुआ?",
         "options_en": ["Quit India Movement", "Salt March", "Khilafat", "Swadeshi"],
         "options_hi": ["भारत छोड़ो आंदोलन", "नमक यात्रा", "ख़िलाफ़त", "स्वदेशी"], "answer": 0},
        {"q_en": "Aruna is lovingly known as?", "q_hi": "अरुणा को प्यार से क्या कहा जाता है?",
         "options_en": ["The Grand Old Lady of Independence", "Mother India", "Veerangana", "Queen Mum"],
         "options_hi": ["आज़ादी की महान बुज़ुर्ग महिला", "भारत माता", "वीरांगना", "क्वीन मॉम"], "answer": 0},
        {"q_en": "She was wife of which leader?", "q_hi": "वह किस नेता की पत्नी थीं?",
         "options_en": ["Asaf Ali (lawyer & freedom fighter)", "Subhas Bose", "Jawaharlal Nehru", "Sardar Patel"],
         "options_hi": ["आसफ अली (वकील व स्वतंत्रता सेनानी)", "सुभाष बोस", "जवाहरलाल नेहरू", "सरदार पटेल"], "answer": 0},
        {"q_en": "Aruna was awarded which posthumous honour?", "q_hi": "अरुणा को मरणोपरांत कौन सा सम्मान मिला?",
         "options_en": ["Bharat Ratna", "Padma Shri only", "No award", "Nobel Prize"],
         "options_hi": ["भारत रत्न", "केवल पद्म श्री", "कोई पुरस्कार नहीं", "नोबेल पुरस्कार"], "answer": 0},
    ],
    "kalpana-datta": [
        {"q_en": "Kalpana Datta took part in which 1930 raid?", "q_hi": "कल्पना दत्ता ने 1930 के किस छापे में भाग लिया?",
         "options_en": ["Chittagong Armoury Raid", "Salt March", "Kakori Train", "Surat Split"],
         "options_hi": ["चटगाँव शस्त्रागार छापा", "नमक यात्रा", "काकोरी ट्रेन", "सूरत विभाजन"], "answer": 0},
        {"q_en": "Who was her mentor during the raid?", "q_hi": "छापे के दौरान उनके गुरु कौन थे?",
         "options_en": ["Surya Sen (Master-da)", "Subhas Bose", "Bhagat Singh", "Gandhi"],
         "options_hi": ["सूर्य सेन (मास्टर-दा)", "सुभाष बोस", "भगत सिंह", "गांधी"], "answer": 0},
        {"q_en": "How did Kalpana disguise herself?", "q_hi": "कल्पना ने ख़ुद को कैसे छुपाया?",
         "options_en": ["Dressed as a boy", "Dressed as nurse", "Dressed as priest", "Dressed as merchant"],
         "options_hi": ["लड़के के भेस में", "नर्स के भेस में", "पुजारी के भेस में", "व्यापारी के भेस में"], "answer": 0},
        {"q_en": "Kalpana Datta was from which Indian state?", "q_hi": "कल्पना दत्ता किस राज्य से थीं?",
         "options_en": ["Bengal", "Bihar", "Punjab", "Maharashtra"],
         "options_hi": ["बंगाल", "बिहार", "पंजाब", "महाराष्ट्र"], "answer": 0},
        {"q_en": "Her bravery was a sign that GIRLS could do what?", "q_hi": "उनकी वीरता ने दिखाया कि लड़कियाँ क्या कर सकती हैं?",
         "options_en": ["Be revolutionary warriors", "Only cook", "Only sing", "Stay at home"],
         "options_hi": ["क्रांतिकारी योद्धा बन सकती हैं", "केवल पकाएँ", "केवल गाएँ", "घर रहें"], "answer": 0},
    ],
    "birsa-munda": [
        {"q_en": "By what name is Birsa Munda revered?", "q_hi": "बिरसा मुंडा को किस नाम से पूजा जाता है?",
         "options_en": ["Dharti Aaba (Father of Earth)", "Lok Pita", "Veer Yuvraj", "Aadi Guru"],
         "options_hi": ["धरती आबा (पृथ्वी पिता)", "लोक पिता", "वीर युवराज", "आदि गुरु"], "answer": 0},
        {"q_en": "Birsa was a hero of which tribal community?", "q_hi": "बिरसा किस आदिवासी समुदाय के नायक थे?",
         "options_en": ["Munda tribe", "Santhal tribe", "Bhil tribe", "Naga tribe"],
         "options_hi": ["मुंडा जनजाति", "संथाल जनजाति", "भील जनजाति", "नागा जनजाति"], "answer": 0},
        {"q_en": "From which Indian state was Birsa?", "q_hi": "बिरसा किस राज्य से थे?",
         "options_en": ["Jharkhand", "Odisha", "Madhya Pradesh", "Chhattisgarh"],
         "options_hi": ["झारखंड", "ओडिशा", "मध्य प्रदेश", "छत्तीसगढ़"], "answer": 0},
        {"q_en": "His birthday (15 November) is celebrated as?", "q_hi": "उनका जन्मदिन (15 नवंबर) किस रूप में मनाया जाता है?",
         "options_en": ["Janjatiya Gaurav Divas (Tribal Pride Day)", "Children's Day", "Independence Day", "Republic Day"],
         "options_hi": ["जनजातीय गौरव दिवस", "बाल दिवस", "स्वतंत्रता दिवस", "गणतंत्र दिवस"], "answer": 0},
        {"q_en": "At what young age did Birsa pass away?", "q_hi": "बिरसा का निधन किस उम्र में हुआ?",
         "options_en": ["25", "50", "70", "12"],
         "options_hi": ["25", "50", "70", "12"], "answer": 0},
    ],
    "tilka-manjhi": [
        {"q_en": "Tilka Manjhi belonged to which tribe?", "q_hi": "तिलका मांझी किस जनजाति से थे?",
         "options_en": ["Santhal tribe", "Bhil tribe", "Gond tribe", "Naga tribe"],
         "options_hi": ["संथाल जनजाति", "भील जनजाति", "गोंड जनजाति", "नागा जनजाति"], "answer": 0},
        {"q_en": "In which century did he live and fight?", "q_hi": "वे किस सदी में जिए और लड़े?",
         "options_en": ["Late 1700s", "1500s", "1900s", "1300s"],
         "options_hi": ["1700 के अंत में", "1500 के दशक में", "1900 के दशक में", "1300 के दशक में"], "answer": 0},
        {"q_en": "From which region was Tilka Manjhi?", "q_hi": "तिलका मांझी किस क्षेत्र से थे?",
         "options_en": ["Bhagalpur (Bihar/Jharkhand)", "Maharashtra", "Punjab", "Tamil Nadu"],
         "options_hi": ["भागलपुर (बिहार/झारखंड)", "महाराष्ट्र", "पंजाब", "तमिल नाडु"], "answer": 0},
        {"q_en": "Tilka used which weapon as his trademark?", "q_hi": "तिलका का प्रसिद्ध हथियार क्या था?",
         "options_en": ["Bow and arrow", "Sword", "Rifle", "Spear only"],
         "options_hi": ["धनुष और बाण", "तलवार", "बंदूक", "केवल भाला"], "answer": 0},
        {"q_en": "Tilka Manjhi is honoured as one of India's FIRST what?", "q_hi": "तिलका मांझी भारत के सबसे पहले किस के रूप में पूजे जाते हैं?",
         "options_en": ["Tribal freedom fighters", "Poets", "Lawyers", "Merchants"],
         "options_hi": ["आदिवासी स्वतंत्रता सेनानी", "कवि", "वकील", "व्यापारी"], "answer": 0},
    ],
}
