"""Seed data for freedom fighter stories with English + Hindi versions and quizzes."""

STORIES = [
    {
        "id": "bhagat-singh",
        "name": "Bhagat Singh",
        "title_en": "Bhagat Singh: The Roar of a Young Lion",
        "title_hi": "भगत सिंह: एक नौजवान शेर की दहाड़",
        "tagline_en": "Inquilab Zindabad! The young revolutionary who ignited a generation.",
        "tagline_hi": "इंक़लाब ज़िंदाबाद! वह नौजवान क्रांतिकारी जिसने एक पीढ़ी को जगाया।",
        "era": "1907 - 1931",
        "color": "#D72638",
        "story_en": "In a small village in Punjab, a brave little boy named Bhagat Singh once planted tiny guns in his garden. When his uncle asked why, Bhagat smiled and said, 'I am growing guns to free our country!' Even as a child, his heart burned for India's freedom. As he grew older, Bhagat read books from around the world and dreamed of a free India where everyone — rich or poor — would live with dignity. When the British rulers passed unfair laws, young Bhagat and his friends decided to make their voices heard. They threw harmless smoke bombs in the assembly and shouted, 'Inquilab Zindabad!' which means 'Long Live the Revolution!' Bhagat did not run away. He wanted to be caught so he could tell the world about India's pain. In jail, he read books, wrote letters, and inspired thousands. At just 23 years old, he gave his life with a smile, becoming one of India's most loved heroes. His courage teaches us that age is just a number — even young people can change the world.",
        "story_hi": "पंजाब के एक छोटे से गाँव में एक बहादुर लड़का था भगत सिंह। एक बार उसने अपने बगीचे में छोटी-छोटी बंदूकें बोईं। चाचा ने पूछा क्यों, तो भगत मुस्कुराया और बोला, 'मैं देश को आज़ाद कराने के लिए बंदूकें उगा रहा हूँ!' बचपन से ही उसका दिल भारत की आज़ादी के लिए धड़कता था। बड़े होकर भगत ने दुनिया भर की किताबें पढ़ीं और एक ऐसे आज़ाद भारत का सपना देखा जहाँ अमीर-गरीब सब सम्मान से जिएँ। जब अंग्रेज़ों ने अन्यायपूर्ण कानून बनाए, तो भगत और उसके दोस्तों ने अपनी आवाज़ बुलंद करने का फैसला किया। उन्होंने असेंबली में बेज़रर बम फेंके और नारा लगाया, 'इंक़लाब ज़िंदाबाद!' भगत भागे नहीं — वे पकड़े जाना चाहते थे ताकि दुनिया को भारत का दर्द बता सकें। जेल में उन्होंने किताबें पढ़ीं, चिट्ठियाँ लिखीं, और हज़ारों को प्रेरित किया। मात्र 23 वर्ष की उम्र में, उन्होंने मुस्कुराते हुए अपनी जान दे दी और भारत के सबसे प्यारे नायकों में से एक बन गए। उनका साहस सिखाता है कि उम्र सिर्फ़ एक संख्या है — नौजवान भी दुनिया बदल सकते हैं।",
        "quiz": [
            {"q_en": "What did young Bhagat Singh plant in his garden?", "q_hi": "नन्हे भगत सिंह ने बगीचे में क्या बोया था?", "options_en": ["Flowers", "Tiny guns", "Mango seeds", "Vegetables"], "options_hi": ["फूल", "छोटी बंदूकें", "आम के बीज", "सब्ज़ियाँ"], "answer": 1},
            {"q_en": "What slogan did Bhagat Singh shout in the assembly?", "q_hi": "असेंबली में भगत सिंह ने कौन सा नारा लगाया?", "options_en": ["Jai Hind", "Vande Mataram", "Inquilab Zindabad", "Bharat Mata Ki Jai"], "options_hi": ["जय हिंद", "वंदे मातरम्", "इंक़लाब ज़िंदाबाद", "भारत माता की जय"], "answer": 2},
            {"q_en": "How old was Bhagat Singh when he gave his life?", "q_hi": "बलिदान के समय भगत सिंह की उम्र कितनी थी?", "options_en": ["16", "20", "23", "30"], "options_hi": ["16", "20", "23", "30"], "answer": 2},
            {"q_en": "What did Bhagat Singh love doing in jail?", "q_hi": "जेल में भगत सिंह को क्या करना पसंद था?", "options_en": ["Sleeping", "Reading books", "Cooking", "Singing"], "options_hi": ["सोना", "किताबें पढ़ना", "खाना बनाना", "गाना"], "answer": 1},
            {"q_en": "Bhagat Singh teaches us that...", "q_hi": "भगत सिंह हमें सिखाते हैं कि...", "options_en": ["Only adults can change the world", "Age is just a number", "Books are not important", "Fear is good"], "options_hi": ["केवल बड़े दुनिया बदल सकते हैं", "उम्र केवल एक संख्या है", "किताबें ज़रूरी नहीं", "डर अच्छा है"], "answer": 1},
        ],
    },
    {
        "id": "rani-lakshmibai",
        "name": "Rani Lakshmibai",
        "title_en": "Rani Lakshmibai: The Warrior Queen of Jhansi",
        "title_hi": "रानी लक्ष्मीबाई: झाँसी की वीर रानी",
        "tagline_en": "Main apni Jhansi nahi doongi! The queen who rode into battle with her child on her back.",
        "tagline_hi": "मैं अपनी झाँसी नहीं दूँगी! वह रानी जो अपने बच्चे को पीठ पर बाँधकर युद्ध में कूद पड़ी।",
        "era": "1828 - 1858",
        "color": "#7B1FA2",
        "story_en": "Long ago in the kingdom of Jhansi lived a brave girl named Manikarnika, lovingly called Manu. She loved horse riding, sword fighting, and reading — things many girls weren't allowed to do back then. When she grew up, she became the Queen of Jhansi and people called her Rani Lakshmibai. The British wanted to take her kingdom away. They told her, 'Give us Jhansi.' But the Rani stood tall and said, 'Main apni Jhansi nahi doongi!' — 'I will not give up my Jhansi!' She trained her own army of women warriors, including her dear friends Jhalkari Bai and Mundar. With her little adopted son Damodar tied safely on her back, she rode her white horse into battle, swords flashing in both hands. She fought so bravely that even British soldiers said she was the bravest woman they had ever seen. She gave her life protecting her people and became forever the symbol of fierce love and courage. The Rani teaches us: protect what you love, and never let anyone tell you what you cannot do.",
        "story_hi": "बहुत समय पहले झाँसी राज्य में एक बहादुर लड़की रहती थी जिसका नाम मणिकर्णिका था, सब उसे प्यार से 'मनु' कहते। उसे घुड़सवारी, तलवारबाज़ी और पढ़ाई बहुत पसंद थी — ऐसी चीज़ें जो उस ज़माने में लड़कियों को करने नहीं दी जाती थीं। बड़ी होकर वह झाँसी की रानी बनी और लोग उसे रानी लक्ष्मीबाई कहने लगे। अंग्रेज़ उसका राज्य छीनना चाहते थे। उन्होंने कहा, 'झाँसी हमें दे दो।' पर रानी ने सीना तानकर कहा, 'मैं अपनी झाँसी नहीं दूँगी!' उन्होंने झलकारी बाई और मुंदर जैसी सहेलियों के साथ महिला सैनिकों की अपनी सेना तैयार की। नन्हे दत्तक पुत्र दामोदर को पीठ पर बाँधकर, सफ़ेद घोड़े पर सवार होकर, दोनों हाथों में तलवारें चमकाते हुए वह युद्ध के मैदान में कूद पड़ीं। वे इतनी बहादुरी से लड़ीं कि अंग्रेज़ सैनिकों ने भी कहा कि वे सबसे वीर महिला हैं। अपने लोगों की रक्षा करते हुए उन्होंने प्राण न्योछावर कर दिए और हमेशा के लिए साहस और प्रेम का प्रतीक बन गईं। रानी हमें सिखाती हैं — जिसे प्यार करो, उसकी रक्षा करो, और कभी किसी को मत कहने दो कि तुम क्या नहीं कर सकते।",
        "quiz": [
            {"q_en": "What was Rani Lakshmibai's childhood name?", "q_hi": "रानी लक्ष्मीबाई का बचपन का नाम क्या था?", "options_en": ["Lakshmi", "Manikarnika", "Damodar", "Jhalkari"], "options_hi": ["लक्ष्मी", "मणिकर्णिका", "दामोदर", "झलकारी"], "answer": 1},
            {"q_en": "Who did Rani Lakshmibai carry on her back during battle?", "q_hi": "युद्ध में रानी ने अपनी पीठ पर किसे बाँधा?", "options_en": ["Her husband", "Her son Damodar", "A flag", "A treasure"], "options_hi": ["अपने पति को", "बेटे दामोदर को", "एक झंडा", "खज़ाना"], "answer": 1},
            {"q_en": "Which famous words did the Rani say?", "q_hi": "रानी ने कौन से प्रसिद्ध शब्द कहे?", "options_en": ["Jai Jhansi", "I will not give up my Jhansi", "Save India", "Run away"], "options_hi": ["जय झाँसी", "मैं अपनी झाँसी नहीं दूँगी", "भारत बचाओ", "भाग जाओ"], "answer": 1},
            {"q_en": "What kingdom did the Rani rule?", "q_hi": "रानी किस राज्य की शासक थीं?", "options_en": ["Delhi", "Jhansi", "Mysore", "Punjab"], "options_hi": ["दिल्ली", "झाँसी", "मैसूर", "पंजाब"], "answer": 1},
            {"q_en": "Who was Jhalkari Bai?", "q_hi": "झलकारी बाई कौन थीं?", "options_en": ["A British soldier", "Rani's friend & warrior", "A queen of Delhi", "A teacher"], "options_hi": ["एक अंग्रेज़ सैनिक", "रानी की सहेली व योद्धा", "दिल्ली की रानी", "शिक्षिका"], "answer": 1},
        ],
    },
    {
        "id": "mahatma-gandhi",
        "name": "Mahatma Gandhi",
        "title_en": "Mahatma Gandhi: The Salt of Freedom",
        "title_hi": "महात्मा गांधी: आज़ादी का नमक",
        "tagline_en": "He fought the mightiest empire with truth, salt, and a smile.",
        "tagline_hi": "उन्होंने सबसे बड़ी सत्ता को सत्य, नमक और मुस्कान से हराया।",
        "era": "1869 - 1948",
        "color": "#138808",
        "story_en": "Once upon a time, a thin man with round glasses, a walking stick, and a kind smile changed the world without ever picking up a weapon. His name was Mohandas Karamchand Gandhi — but everyone called him Bapu, meaning 'father.' As a child, Mohan was shy and afraid of the dark. But he loved truth more than anything. One day, he ate something he wasn't supposed to and felt so guilty that he wrote a letter to his father confessing everything. His father forgave him with tears, and Mohan learned the magical power of honesty. When he grew up, Bapu saw how the British treated Indians unfairly. So he taught India something amazing: 'Ahimsa' — fight without hitting. 'Satyagraha' — hold on to truth. When the British made it illegal to make salt, Bapu walked 240 miles to the sea! Thousands joined him. He picked up a fistful of salt and said, 'With this salt, I shake the foundations of an Empire.' His simple ways — spinning his own clothes, eating little, loving everyone — inspired millions. India became free in 1947 because of leaders like Bapu. He teaches us that gentleness can be stronger than the strongest sword.",
        "story_hi": "एक समय की बात है, एक दुबला-पतला आदमी जिसकी गोल ऐनक, लाठी और मीठी मुस्कान थी, उसने बिना हथियार उठाए दुनिया बदल दी। उनका नाम था मोहनदास करमचंद गांधी — पर सब उन्हें बापू कहते थे, यानी 'पिता।' बचपन में मोहन शर्मीले थे और अंधेरे से डरते थे। पर सच्चाई उन्हें सबसे ज़्यादा प्यारी थी। एक दिन उन्होंने कुछ ऐसा खाया जो नहीं खाना चाहिए था और इतना अपराधबोध हुआ कि उन्होंने अपने पिता को चिट्ठी लिखकर सब कबूल कर लिया। पिता ने आँसुओं के साथ माफ़ कर दिया, और मोहन को ईमानदारी की जादुई शक्ति का पता चला। बड़े होकर बापू ने देखा कि अंग्रेज़ भारतीयों के साथ कितना अन्याय करते हैं। उन्होंने भारत को कुछ अद्भुत सिखाया: 'अहिंसा' — बिना मारे लड़ाई, और 'सत्याग्रह' — सत्य पर अडिग रहना। जब अंग्रेज़ों ने नमक बनाना ग़ैरक़ानूनी कर दिया, तो बापू समुद्र तक 240 मील पैदल चले! हज़ारों लोग उनके साथ चले। उन्होंने मुट्ठी भर नमक उठाकर कहा, 'इस नमक से मैं साम्राज्य की नींव हिला रहा हूँ।' उनके सरल तरीके — खुद कपड़े कातना, कम खाना, सबसे प्यार करना — करोड़ों को प्रेरित कर गए। बापू जैसे नेताओं की वजह से 1947 में भारत आज़ाद हुआ। वे सिखाते हैं कि कोमलता सबसे तेज़ तलवार से भी मज़बूत हो सकती है।",
        "quiz": [
            {"q_en": "What did people lovingly call Gandhi?", "q_hi": "लोग गांधी जी को प्यार से क्या कहते थे?", "options_en": ["Babu", "Bapu", "Beta", "Bhau"], "options_hi": ["बाबू", "बापू", "बेटा", "भाऊ"], "answer": 1},
            {"q_en": "What does 'Ahimsa' mean?", "q_hi": "'अहिंसा' का क्या अर्थ है?", "options_en": ["War", "Non-violence", "Truth", "Fasting"], "options_hi": ["युद्ध", "अहिंसा / बिना मारे", "सत्य", "उपवास"], "answer": 1},
            {"q_en": "How far did Gandhi walk for the Salt March?", "q_hi": "गांधी जी ने नमक यात्रा में कितनी दूरी तय की?", "options_en": ["10 miles", "100 miles", "240 miles", "500 miles"], "options_hi": ["10 मील", "100 मील", "240 मील", "500 मील"], "answer": 2},
            {"q_en": "What did Gandhi like to spin himself?", "q_hi": "गांधी जी क्या ख़ुद कातते थे?", "options_en": ["Wool", "Cotton thread (Khadi)", "Silk", "Plastic"], "options_hi": ["ऊन", "सूत (खादी)", "रेशम", "प्लास्टिक"], "answer": 1},
            {"q_en": "In which year did India become free?", "q_hi": "भारत किस वर्ष आज़ाद हुआ?", "options_en": ["1942", "1947", "1950", "1857"], "options_hi": ["1942", "1947", "1950", "1857"], "answer": 1},
        ],
    },
    {
        "id": "subhas-bose",
        "name": "Subhas Chandra Bose",
        "title_en": "Netaji Subhas Chandra Bose: Give Me Blood, I'll Give You Freedom",
        "title_hi": "नेताजी सुभाष चंद्र बोस: तुम मुझे ख़ून दो, मैं तुम्हें आज़ादी दूँगा",
        "tagline_en": "The fearless leader who built an army across oceans for India.",
        "tagline_hi": "वह निर्भीक नेता जिन्होंने सात समंदर पार भारत के लिए सेना बनाई।",
        "era": "1897 - 1945",
        "color": "#1A365D",
        "story_en": "In a big family in Cuttack, a curious boy named Subhas grew up loving books and stories of brave warriors. He was so smart that he topped almost every exam, and he could have become a rich officer for the British. But Subhas said, 'No! I will not work for those who hurt my country.' He left his fancy job and joined India's freedom struggle. People started calling him 'Netaji' — meaning 'Respected Leader.' Netaji believed India needed brave action. When World War II began, he traveled in secret — disguised, by submarine, through forests — to faraway lands like Germany and Japan. There, he gathered Indians living abroad and built the Azad Hind Fauj — the Indian National Army (INA). Women too joined as soldiers in the Rani Jhansi Regiment! Netaji thundered to his soldiers, 'Tum mujhe khoon do, main tumhe azaadi doonga!' — 'Give me blood, and I will give you freedom!' He marched towards India, calling out 'Chalo Dilli!' — 'On to Delhi!' Though he disappeared mysteriously, his fire lit India's heart and helped bring freedom. He shows us that bold dreams plus brave action can move mountains.",
        "story_hi": "कटक के एक बड़े परिवार में सुभाष नाम का जिज्ञासु बच्चा रहता था जिसे किताबें और वीरों की कहानियाँ बहुत पसंद थीं। वह इतने होशियार थे कि लगभग हर परीक्षा में अव्वल आते थे, और चाहते तो अंग्रेज़ों के बड़े अफ़सर बन सकते थे। पर सुभाष ने कहा, 'नहीं! मैं उनके लिए काम नहीं करूँगा जो मेरे देश को सता रहे हैं।' उन्होंने ऊँची नौकरी छोड़कर आज़ादी की लड़ाई शुरू कर दी। लोग उन्हें 'नेताजी' कहने लगे — यानी 'सम्मानित नेता।' नेताजी मानते थे कि भारत को वीरता चाहिए। जब दूसरा विश्वयुद्ध शुरू हुआ, तो वे चुपके से भेस बदलकर, पनडुब्बी से, जंगलों के रास्ते जर्मनी और जापान जैसे दूर देशों में पहुँचे। वहाँ रह रहे भारतीयों को इकट्ठा करके उन्होंने 'आज़ाद हिंद फ़ौज' (INA) बनाई। महिलाएँ भी 'रानी झाँसी रेजिमेंट' में सैनिक बनीं! नेताजी ने सैनिकों से गरजकर कहा, 'तुम मुझे ख़ून दो, मैं तुम्हें आज़ादी दूँगा!' वे 'चलो दिल्ली!' का नारा देते हुए भारत की ओर बढ़े। हालाँकि वे रहस्यमयी ढंग से लापता हो गए, उनकी आग ने भारत के दिल को जलाया और आज़ादी लाने में मदद की। वे सिखाते हैं कि बड़े सपने और बहादुरी पहाड़ हिला सकते हैं।",
        "quiz": [
            {"q_en": "What does 'Netaji' mean?", "q_hi": "'नेताजी' का अर्थ क्या है?", "options_en": ["Soldier", "Respected Leader", "Rich man", "Teacher"], "options_hi": ["सैनिक", "सम्मानित नेता", "धनी व्यक्ति", "शिक्षक"], "answer": 1},
            {"q_en": "What army did Netaji build?", "q_hi": "नेताजी ने कौन सी सेना बनाई?", "options_en": ["British Army", "Azad Hind Fauj (INA)", "Mughal Army", "Maratha Army"], "options_hi": ["ब्रिटिश सेना", "आज़ाद हिंद फ़ौज (INA)", "मुग़ल सेना", "मराठा सेना"], "answer": 1},
            {"q_en": "What was his famous battle cry?", "q_hi": "उनका प्रसिद्ध युद्ध-घोष क्या था?", "options_en": ["Vande Mataram", "Chalo Dilli", "Jai Bharat", "Hindi Hind"], "options_hi": ["वंदे मातरम्", "चलो दिल्ली", "जय भारत", "हिंदी हिंद"], "answer": 1},
            {"q_en": "Where was Subhas Chandra Bose born?", "q_hi": "सुभाष चंद्र बोस का जन्म कहाँ हुआ?", "options_en": ["Delhi", "Cuttack", "Mumbai", "Madras"], "options_hi": ["दिल्ली", "कटक", "मुंबई", "मद्रास"], "answer": 1},
            {"q_en": "Did women fight in Netaji's army?", "q_hi": "क्या नेताजी की सेना में महिलाएँ लड़ीं?", "options_en": ["No, never", "Yes, in Rani Jhansi Regiment", "Only as nurses", "Only as cooks"], "options_hi": ["नहीं", "हाँ, रानी झाँसी रेजिमेंट में", "केवल नर्स के रूप में", "केवल रसोइये के रूप में"], "answer": 1},
        ],
    },
    {
        "id": "sarojini-naidu",
        "name": "Sarojini Naidu",
        "title_en": "Sarojini Naidu: The Nightingale of India",
        "title_hi": "सरोजिनी नायडू: भारत की कोकिला",
        "tagline_en": "The poet-leader whose words sang freedom into Indian hearts.",
        "tagline_hi": "वह कवयित्री-नेता जिनके शब्दों ने भारतीय दिलों में आज़ादी का गीत गाया।",
        "era": "1879 - 1949",
        "color": "#F4A261",
        "story_en": "In Hyderabad lived a tiny girl named Sarojini who wrote her first poem when she was just 11 years old! Words flowed from her like a river. She read in many languages — English, Urdu, Telugu, Bengali, Persian. People said her poems were like sweet songs, so they called her 'Bharat Kokila' — the Nightingale of India. But Sarojini was more than a poet. When India was struggling under British rule, she stood up and said, 'A country's greatness lies in its undying ideals of love and sacrifice.' She joined Mahatma Gandhi in the freedom movement and led brave salt protests where she was arrested again and again — but never afraid! She traveled across India inspiring girls to study, dream, and lead. After freedom, she became the first woman Governor of an Indian state (Uttar Pradesh). She showed that a pen and a voice can be as powerful as any weapon. From her, we learn: words have wings — use them to lift up your country and your people.",
        "story_hi": "हैदराबाद में सरोजिनी नाम की एक नन्ही लड़की रहती थी जिसने सिर्फ़ 11 साल की उम्र में अपनी पहली कविता लिख डाली! शब्द उससे नदी की तरह बहते थे। वह कई भाषाएँ पढ़ती थी — अंग्रेज़ी, उर्दू, तेलुगु, बंगाली, फ़ारसी। लोग कहते उसकी कविताएँ मीठे गीत जैसी हैं, इसलिए उन्हें 'भारत कोकिला' कहा गया। पर सरोजिनी सिर्फ़ कवयित्री नहीं थीं। जब भारत अंग्रेज़ों के शासन में पिस रहा था, तो उन्होंने खड़े होकर कहा, 'किसी देश की महानता उसके प्रेम और बलिदान के अमर आदर्शों में है।' उन्होंने महात्मा गांधी के साथ आज़ादी की लड़ाई में हिस्सा लिया और साहसी नमक आंदोलनों का नेतृत्व किया, जहाँ वे बार-बार गिरफ़्तार हुईं — पर कभी डरीं नहीं! उन्होंने भारत भर घूमकर लड़कियों को पढ़ने, सपने देखने और नेतृत्व करने की प्रेरणा दी। आज़ादी के बाद वे एक भारतीय राज्य (उत्तर प्रदेश) की पहली महिला राज्यपाल बनीं। उन्होंने दिखाया कि क़लम और आवाज़ किसी भी हथियार जितनी ताक़तवर हो सकती है। उनसे हम सीखते हैं — शब्दों के पंख होते हैं, इनसे अपने देश और लोगों को ऊँचा उठाओ।",
        "quiz": [
            {"q_en": "What was Sarojini Naidu fondly called?", "q_hi": "सरोजिनी नायडू को प्यार से क्या कहा जाता था?", "options_en": ["Iron Lady", "Nightingale of India", "Queen of Songs", "Star of Hyderabad"], "options_hi": ["लौह महिला", "भारत कोकिला", "गीतों की रानी", "हैदराबाद का सितारा"], "answer": 1},
            {"q_en": "At what age did she write her first poem?", "q_hi": "उन्होंने पहली कविता किस उम्र में लिखी?", "options_en": ["7", "11", "16", "20"], "options_hi": ["7", "11", "16", "20"], "answer": 1},
            {"q_en": "Which leader did she join in the freedom struggle?", "q_hi": "वे किस नेता के साथ आज़ादी की लड़ाई में जुड़ीं?", "options_en": ["Bhagat Singh", "Mahatma Gandhi", "Bose", "Tilak"], "options_hi": ["भगत सिंह", "महात्मा गांधी", "बोस", "तिलक"], "answer": 1},
            {"q_en": "She became the first woman Governor of which state?", "q_hi": "वे किस राज्य की पहली महिला राज्यपाल बनीं?", "options_en": ["Bihar", "Uttar Pradesh", "Bengal", "Punjab"], "options_hi": ["बिहार", "उत्तर प्रदेश", "बंगाल", "पंजाब"], "answer": 1},
            {"q_en": "What lesson does Sarojini teach us?", "q_hi": "सरोजिनी हमें क्या सिखाती हैं?", "options_en": ["Words have wings", "Always be silent", "Money matters most", "Fight everyone"], "options_hi": ["शब्दों के पंख होते हैं", "हमेशा चुप रहो", "पैसा सबसे ज़रूरी है", "सबसे लड़ो"], "answer": 0},
        ],
    },
    {
        "id": "chandrashekhar-azad",
        "name": "Chandrashekhar Azad",
        "title_en": "Chandrashekhar Azad: Forever Free",
        "title_hi": "चंद्रशेखर आज़ाद: सदा आज़ाद",
        "tagline_en": "He promised never to be captured — and he kept his word.",
        "tagline_hi": "उन्होंने वादा किया कि कभी पकड़े नहीं जाएँगे — और वादा निभाया।",
        "era": "1906 - 1931",
        "color": "#B8860B",
        "story_en": "When Chandrashekhar was just 15 years old, the British caught him during a protest. The judge thundered, 'What is your name?' The boy stood straight and said, 'My name is Azad — Free!' 'Father's name?' 'Swatantrata — Independence!' 'Address?' 'Jail!' The court was shocked. From that day, the world called him Chandrashekhar Azad. Azad made a promise to himself and his mother that he would never be caught alive by the British. He could shoot, swim, run, and hide better than anyone. He trained young revolutionaries in secret forests, teaching them to be fearless and to love their country more than their lives. He worked with Bhagat Singh and many others, planning brave actions to wake India up. One day in Allahabad's Alfred Park (now called Azad Park), British police surrounded him. Azad fought back alone, like a tiger, until only one bullet remained in his pistol. Keeping his promise, he used that final bullet himself rather than be captured. He stayed free, just like his name. Azad's story tells us: keep your promises, and live by your name — make it mean something powerful.",
        "story_hi": "जब चंद्रशेखर सिर्फ़ 15 साल के थे, अंग्रेज़ों ने उन्हें एक प्रदर्शन में पकड़ लिया। जज ने ज़ोर से पूछा, 'तुम्हारा नाम क्या है?' लड़का सीना तानकर बोला, 'मेरा नाम आज़ाद है!' 'पिता का नाम?' 'स्वतंत्रता!' 'पता?' 'जेल!' अदालत हैरान रह गई। उस दिन से दुनिया उन्हें चंद्रशेखर आज़ाद कहने लगी। आज़ाद ने अपनी माँ और ख़ुद से वादा किया कि वे कभी जीवित अंग्रेज़ों के हाथ नहीं लगेंगे। वे शूटिंग, तैराकी, दौड़ और छिपने में बेजोड़ थे। वे जंगलों में नौजवान क्रांतिकारियों को निर्भीक होना और देश को जान से ज़्यादा प्यार करना सिखाते। उन्होंने भगत सिंह और कई साथियों के साथ मिलकर भारत को जगाने की वीर योजनाएँ बनाईं। एक दिन इलाहाबाद के अल्फ्रेड पार्क (अब आज़ाद पार्क) में अंग्रेज़ पुलिस ने उन्हें घेर लिया। आज़ाद अकेले शेर की तरह लड़े, जब तक पिस्तौल में आख़िरी गोली न बची। अपना वादा निभाते हुए, उन्होंने वह आख़िरी गोली ख़ुद पर चला दी और पकड़े नहीं गए। वे आज़ाद रहे — जैसा उनका नाम था। आज़ाद की कहानी सिखाती है: वादे निभाओ, और अपने नाम के अनुसार जिओ — उसे ताक़तवर बनाओ।",
        "quiz": [
            {"q_en": "What name did Chandrashekhar give the judge?", "q_hi": "चंद्रशेखर ने जज को कौन सा नाम बताया?", "options_en": ["Ram", "Azad", "Bhagat", "Subhash"], "options_hi": ["राम", "आज़ाद", "भगत", "सुभाष"], "answer": 1},
            {"q_en": "What 'address' did he tell the court?", "q_hi": "उन्होंने कोर्ट में कौन सा 'पता' बताया?", "options_en": ["Home", "Jail", "School", "Forest"], "options_hi": ["घर", "जेल", "स्कूल", "जंगल"], "answer": 1},
            {"q_en": "What promise did Azad keep?", "q_hi": "आज़ाद ने कौन सा वादा निभाया?", "options_en": ["To never sleep", "Never be caught alive", "Never eat sugar", "Always run"], "options_hi": ["कभी न सोना", "जीवित कभी न पकड़े जाना", "मीठा न खाना", "हमेशा भागना"], "answer": 1},
            {"q_en": "Which park is now named after him?", "q_hi": "अब कौन सा पार्क उनके नाम पर है?", "options_en": ["Lodhi Park", "Azad Park", "Cubbon Park", "Hyde Park"], "options_hi": ["लोधी पार्क", "आज़ाद पार्क", "कब्बन पार्क", "हाइड पार्क"], "answer": 1},
            {"q_en": "Which freedom fighter did Azad work with?", "q_hi": "आज़ाद किस क्रांतिकारी के साथ काम करते थे?", "options_en": ["Gandhi", "Bhagat Singh", "Sardar Patel", "Tilak"], "options_hi": ["गांधी", "भगत सिंह", "सरदार पटेल", "तिलक"], "answer": 1},
        ],
    },
    {
        "id": "mangal-pandey",
        "name": "Mangal Pandey",
        "title_en": "Mangal Pandey: The First Spark",
        "title_hi": "मंगल पांडे: पहली चिंगारी",
        "tagline_en": "The brave soldier who lit the spark of India's first freedom fight.",
        "tagline_hi": "वह बहादुर सिपाही जिसने भारत की पहली आज़ादी की लड़ाई की चिंगारी जलाई।",
        "era": "1827 - 1857",
        "color": "#D72638",
        "story_en": "In a quiet village in Uttar Pradesh, a strong young man named Mangal Pandey worked as a soldier — a 'sepoy' — for the British East India Company. He was tall, brave, and proud of his traditions. But one day, news spread that the new bullets the British gave them were greased with cow and pig fat. To use them, the soldiers had to bite the bullets — something that hurt the religious feelings of both Hindu and Muslim sepoys. Mangal felt insulted. On 29th March 1857, he stood up against his British officers in Barrackpore. With his musket in hand, he shouted to his fellow soldiers, 'Brothers, rise! Free yourselves from this slavery!' He fought bravely, alone — until he was overpowered. The British hanged him, but his courage flew across India like wildfire. His one act of bravery sparked the great Revolt of 1857 — India's First War of Independence! Though Mangal was just one man, his tiny spark started a flame that lit the freedom struggle for the next 90 years. He teaches us: never let anyone hurt your dignity. Sometimes one brave voice is all it takes to wake up a nation.",
        "story_hi": "उत्तर प्रदेश के एक शांत गाँव में मंगल पांडे नाम का एक मज़बूत नौजवान अंग्रेज़ ईस्ट इंडिया कंपनी की सेना में 'सिपाही' था। वह लंबा, वीर और अपनी परंपराओं पर गर्व करने वाला था। पर एक दिन ख़बर फैली कि अंग्रेज़ों ने जो नई गोलियाँ दी हैं, उन पर गाय और सूअर की चर्बी लगी है। उन्हें इस्तेमाल करने के लिए सिपाहियों को मुँह से काटना पड़ता था — जो हिंदू-मुसलमान दोनों की आस्था को ठेस पहुँचाता। मंगल को यह अपमान असहनीय लगा। 29 मार्च 1857 को बैरकपुर में उन्होंने अंग्रेज़ अफ़सरों के ख़िलाफ़ बग़ावत कर दी। बंदूक हाथ में लेकर वे साथी सिपाहियों से चिल्लाए, 'भाइयो, उठो! इस ग़ुलामी से आज़ाद हो जाओ!' वे अकेले बहादुरी से लड़े — जब तक उन्हें क़ाबू न कर लिया गया। अंग्रेज़ों ने उन्हें फाँसी दे दी, पर उनकी वीरता आग की तरह पूरे भारत में फैल गई। उनकी एक बहादुरी ने 1857 का महान विद्रोह — भारत का पहला स्वतंत्रता संग्राम — शुरू कर दिया! भले ही मंगल अकेले थे, पर उनकी छोटी चिंगारी ने अगले 90 साल तक आज़ादी की लड़ाई की लौ जलाई। वे सिखाते हैं: अपने स्वाभिमान को कभी ठेस मत लगने दो। कभी-कभी एक बहादुर आवाज़ ही पूरे राष्ट्र को जगा देती है।",
        "quiz": [
            {"q_en": "What was Mangal Pandey's job?", "q_hi": "मंगल पांडे का काम क्या था?", "options_en": ["Farmer", "Sepoy (soldier)", "Teacher", "Trader"], "options_hi": ["किसान", "सिपाही", "शिक्षक", "व्यापारी"], "answer": 1},
            {"q_en": "What was wrong with the new bullets?", "q_hi": "नई गोलियों में क्या समस्या थी?", "options_en": ["Too small", "Greased with animal fat", "Too heavy", "Made of wood"], "options_hi": ["बहुत छोटी", "पशु चर्बी से लिपटी", "बहुत भारी", "लकड़ी की"], "answer": 1},
            {"q_en": "In which year did he revolt?", "q_hi": "उन्होंने किस साल बग़ावत की?", "options_en": ["1757", "1857", "1947", "1900"], "options_hi": ["1757", "1857", "1947", "1900"], "answer": 1},
            {"q_en": "Where did the revolt begin?", "q_hi": "विद्रोह कहाँ शुरू हुआ?", "options_en": ["Delhi", "Barrackpore", "Bombay", "Madras"], "options_hi": ["दिल्ली", "बैरकपुर", "बंबई", "मद्रास"], "answer": 1},
            {"q_en": "What did Mangal Pandey's spark start?", "q_hi": "मंगल पांडे की चिंगारी ने क्या शुरू किया?", "options_en": ["A festival", "First War of Independence", "A school", "A new religion"], "options_hi": ["एक त्योहार", "प्रथम स्वतंत्रता संग्राम", "एक स्कूल", "नया धर्म"], "answer": 1},
        ],
    },
    {
        "id": "bhimrao-ambedkar",
        "name": "Dr. B. R. Ambedkar",
        "title_en": "Dr. B. R. Ambedkar: The Architect of Freedom",
        "title_hi": "डॉ. बी. आर. अंबेडकर: आज़ादी के निर्माता",
        "tagline_en": "He fought for fairness — and wrote the very book of free India.",
        "tagline_hi": "उन्होंने न्याय के लिए लड़ाई लड़ी — और आज़ाद भारत की पुस्तक लिखी।",
        "era": "1891 - 1956",
        "color": "#3949AB",
        "story_en": "A long time ago, a brilliant boy named Bhimrao loved going to school. But because of unfair caste rules, other students didn't let him drink water from the common pot or sit on the same bench. He had to sit alone on a torn cloth on the floor. Many would have given up — but Bhim said, 'I will study so much that no one will ever silence me.' And study he did! He went all the way to America and England, earning so many degrees that people called him 'Dr. Ambedkar.' Babasaheb, as he was lovingly known, dedicated his life to ending unfair treatment of any Indian. He fought for the rights of women, workers, and people from every community. When India became free in 1947, the country needed a new rulebook called the Constitution — and Babasaheb led the team that wrote it! He made sure every Indian — boy or girl, rich or poor, of any caste or religion — would be equal before the law. He even gave women the right to vote and work. From Babasaheb we learn: education is the strongest weapon, and every voice matters in building a fair country.",
        "story_hi": "बहुत समय पहले भीमराव नाम का एक तेज़ बच्चा स्कूल जाना बहुत पसंद करता था। पर अन्यायपूर्ण जाति के नियमों के कारण बाकी बच्चे उसे साथ पानी नहीं पीने देते थे, न साथ बैठने देते थे। उसे ज़मीन पर फटे कपड़े पर अकेले बैठना पड़ता था। कई लोग हार जाते — पर भीम ने कहा, 'मैं इतना पढ़ूँगा कि कोई मुझे चुप नहीं करा सकेगा।' और उन्होंने पढ़ाई की! वे अमेरिका और इंग्लैंड तक गए, इतनी डिग्रियाँ हासिल कीं कि लोग उन्हें 'डॉक्टर अंबेडकर' कहने लगे। बाबासाहेब — जैसा सब प्यार से कहते — ने अपना जीवन हर भारतीय को न्याय दिलाने में लगा दिया। उन्होंने महिलाओं, मज़दूरों और हर समुदाय के लोगों के अधिकारों के लिए लड़ाई लड़ी। 1947 में जब भारत आज़ाद हुआ, तो देश को एक नई किताब चाहिए थी जिसे 'संविधान' कहते हैं — और बाबासाहेब ने उसे लिखने वाली टीम का नेतृत्व किया! उन्होंने सुनिश्चित किया कि हर भारतीय — लड़का हो या लड़की, अमीर हो या ग़रीब, किसी भी जाति या धर्म का — कानून के सामने बराबर हो। उन्होंने महिलाओं को वोट देने और काम करने का अधिकार भी दिलाया। बाबासाहेब से हम सीखते हैं: शिक्षा सबसे मज़बूत हथियार है, और न्यायपूर्ण देश बनाने में हर आवाज़ ज़रूरी है।",
        "quiz": [
            {"q_en": "What did young Bhimrao have to sit on at school?", "q_hi": "स्कूल में नन्हे भीमराव को किस पर बैठना पड़ता था?", "options_en": ["Bench", "Torn cloth on floor", "Soft chair", "Mat"], "options_hi": ["बेंच पर", "फटे कपड़े पर", "गद्देदार कुर्सी पर", "चटाई पर"], "answer": 1},
            {"q_en": "What was Babasaheb's biggest contribution?", "q_hi": "बाबासाहेब का सबसे बड़ा योगदान क्या था?", "options_en": ["Wrote India's Constitution", "Built a fort", "Wrote songs", "Sailed ships"], "options_hi": ["भारत का संविधान लिखा", "एक क़िला बनाया", "गीत लिखे", "जहाज़ चलाए"], "answer": 0},
            {"q_en": "Which countries did he go to study?", "q_hi": "वे पढ़ने किन देशों में गए?", "options_en": ["China and Japan", "USA and England", "France only", "None"], "options_hi": ["चीन और जापान", "अमेरिका और इंग्लैंड", "केवल फ़्रांस", "कहीं नहीं"], "answer": 1},
            {"q_en": "Who did Babasaheb fight for?", "q_hi": "बाबासाहेब किसके लिए लड़े?", "options_en": ["Only kings", "Equality of all Indians", "Only soldiers", "Only farmers"], "options_hi": ["केवल राजा", "सभी भारतीयों की समानता", "केवल सैनिक", "केवल किसान"], "answer": 1},
            {"q_en": "What is the strongest weapon, per Babasaheb?", "q_hi": "बाबासाहेब के अनुसार सबसे मज़बूत हथियार क्या है?", "options_en": ["A sword", "Education", "Money", "Speed"], "options_hi": ["तलवार", "शिक्षा", "पैसा", "गति"], "answer": 1},
        ],
    },
]

BADGES = [
    {"id": "first_story", "name": "First Step", "icon": "footsteps", "desc": "Read your first story"},
    {"id": "five_stories", "name": "Story Explorer", "icon": "book", "desc": "Read 5 stories"},
    {"id": "all_stories", "name": "Freedom Champion", "icon": "trophy", "desc": "Read all 8 stories"},
    {"id": "perfect_quiz", "name": "Truth Seeker", "icon": "star", "desc": "Score 100% on a quiz"},
    {"id": "three_quizzes", "name": "Quiz Master", "icon": "school", "desc": "Complete 3 quizzes"},
    {"id": "streak_3", "name": "Brave Heart", "icon": "flame", "desc": "Maintain a 3-day streak"},
    {"id": "chat_azaadi", "name": "Wise Companion", "icon": "chatbubbles", "desc": "Chat with Azaadi"},
]

LEVELS = [
    {"level": 1, "name": "Young Patriot", "min_xp": 0},
    {"level": 2, "name": "Curious Explorer", "min_xp": 50},
    {"level": 3, "name": "Brave Cadet", "min_xp": 150},
    {"level": 4, "name": "Story Hero", "min_xp": 300},
    {"level": 5, "name": "Truth Warrior", "min_xp": 500},
    {"level": 6, "name": "Freedom Champion", "min_xp": 800},
]


def get_level_for_xp(xp: int):
    current = LEVELS[0]
    for lvl in LEVELS:
        if xp >= lvl["min_xp"]:
            current = lvl
    return current
